### ISSUE TITLE
When passing singleStructInArray params, if there exists map or struct inside the struct, it will be interpret as 'Object'

### ISSUE THREAD

**Issue by lsls01** [ybbus/jsonrpc#21]
When passing singleStructInArray params, if there exists map or struct inside the struct, the map and inner struct will be interpreted as 'Object'. But what I expected is to generate JSON like keys and values recursively to handle complex JSON request.

**Comment by ybbus** [comment]
An example is worth a thousand words

**Comment by lsls01** [comment]
`
type A struct {
	B     string `json:"b"`
	C     D     `json:"c"`
}

type D struct {
	E     string `json:"E"`
	F     string `json:"F"`
}

rpcClient := jsonrpc.NewClient("http://127.0.0.1:3000/")

var a *A

// G and g is the class and parameters variable I used to send this rpc request
rpcClient.CallFor(&a, "sign", []*G{g})
`

After running this code, a.C will get an "object" string as result on the server side. If I use map[string]string to replace struct D, it will get the same result.

If I use g instead of []*G{g}, a.C will be correctly received on the server side, but it's not what I need since there is no brackets around the params.

**Comment by ybbus** [comment]
Sorry, but what exactly does not work for you?
Are you talking about the wrong encoding if json parameters or the wrong decoding of result values?
I also don't know what you mean with "a.C will be correctly received on the server side".
How can a.C be received at server side? It will be used to capture the response.

Can you just explain what you exactly you would expect? Is struct A filled incorrectly? Is the parameter passed incorrectly to the server?

**Comment by lsls01** [comment]
On the server side, what I expected is receiving this params:

params: [{
    "B": "XXXX",
    "C": {
        "E": "XXXX",
        "F": "XXXX"
    }
}]

But the fact is:

params: [{
    "B": "XXXX",
    "C": "Object"
}]

Hope you can understand. I'm so sorry, I didn't explain clearly.

**Comment by s3rj1k** [comment]
@ybbus I believe @lsls01 is talking about nested JSON structure inside params.
Briefly viewed tests, this case is not covered by them.
This should be fixed

**Comment by ybbus** [comment]
I added a test for nested struct and this works as expected:

```go
rpcClient.Call("nestedStruct",
  Planet{
    Name: "Mars",
    Properties: Properties{
      Distance: 54600000,
      Color:    "red",
    },
})
Expect((<-requestChan).body).To(Equal(`{"method":"nestedStruct","params":{"name":"Mars","properties":{"distance":54600000,"color":"red"}},"id":0,"jsonrpc":"2.0"}`))
```

**Comment by ybbus** [comment]
I will close this until you provide a failing test case.
