### ISSUE TITLE
Invalid hardcoded id property in request

### ISSUE THREAD

**Issue by x1unix** [ybbus/jsonrpc#42]
Hello.

Currently, `RPCClient.CallFor` under the hood creates a `RPCRequest` with (uninitialized) zero `.ID` property.

This behavior introduces some issues when communicating with services that use other jsonrpc-server libraries.

In my case, I was communicating with NodeJS-based service which uses [http-jsonrpc-server](https://www.npmjs.com/package/http-jsonrpc-server) package.

When request ID is zero - server just crashes.

I don't know if JSONRPC standard allows zero request ID values and probably I need to address the issue to `http-jsonrpc-server` package author (https://github.com/sangaman/http-jsonrpc-server/issues/19), but this issue might also affect other jsonrpc server implementations.

Can you please use at least `1` as a default value for requests?

The fix should be pretty simple:

**[jsonrpc.go:327](https://github.com/ybbus/jsonrpc/blob/master/jsonrpc.go#L327=)**

 ```diff
func (client *rpcClient) Call(ctx context.Context, method string, params ...interface{}) (*RPCResponse, error) {

	request := &RPCRequest{
+	ID: 1,
		Method:  method,
		Params:  Params(params...),
		JSONRPC: jsonrpcVersion,
	}

	return client.doCall(ctx, request)
}
```

**Comment by ybbus** [comment]
Hi,

json rpc spec unfortunately is not very precise.
But at least:
- "null" is discouraged as value for id, so maybe this could mean, that also for NUMBER ids 0 should not be used
- on all examples of the json rpc spec the requests use id: "1" as first id, this could also hint into that direction

I am not sure if this is a breaking change, but it should not, I guess. Maybe some unit-tests do a hardcoded check against id == 0, but this should not be a big problem to adapt.

Also the server side should not expect a specific id I guess.

So this sounds like a change, that should be ok to introduce.

**Comment by ybbus** [comment]
@x1unix 

See PR: https://github.com/ybbus/jsonrpc/pull/43

I guess this is the least intrusive way.

**Comment by ybbus** [comment]
https://github.com/ybbus/jsonrpc/releases/tag/v3.1.0

@x1unix wish you all the best

**Comment by x1unix** [comment]
@ybbus thank you!
