### ISSUE TITLE
[Enhacement] wrap errors with "%w"

### ISSUE THREAD

**Issue by spali** [ybbus/jsonrpc#46]
Hi 
Thanks for your dead simple library. I'm started to using it.
I have a suggestion to improve the error handling.
If you would wrap all errors (especially the once from third party code), this would help to identify errors.
i.e.:
```go
fmt.Errorf("rpc call: bla bla: %w",err)
```

In my use-case I try to catch the error `context.Canceled` to ignore it, because I cancel the context on purpose on a clean shutdown of all my goroutines.
If wrapper as in the example above, i could just do:
```go
if errors.Is(err, context.Canceled) {
   // ignore
}
```
But currently I need to parse the message.

I'm a hobby go dev, but I started also to do this in all potential reusable code to wrap all third-party errors like that and also provide the my own error as variable like the context package to let user of the library use it for the `error.Is` check: 
```
var Canceled = errors.New("context canceled")
```

As a reference, here the blog that explains this "feature": https://go.dev/blog/go1.13-errors
Regarding chapter "Whether to Wrap".
My interpretation is to wrap errors if you expose anyway the underlying implementation.
And if you don't expose, it could make sense to create your own errors without wrapping.

So for this case the context package implementation is anyway exposed in jsonrpc. So wrapping would make sense.
For http.Client propably you could hide the implementation as you expose only the interface (not checked very code line, but looks like only the interface is exposed, not the implementation of the client).

**Comment by ybbus** [comment]
Hi spali.

Good point,. This also became best practice for my projects.

https://github.com/ybbus/jsonrpc/pull/52

Best,
Alex
