### ISSUE TITLE
[Enhacement] Additional auth parameter in RPC call

### ISSUE THREAD

**Issue by sikmike** [ybbus/jsonrpc#49]
Hi,

is it possible to add an optional **auth** parameter to the RPC call? For example something that would match this JSON Request:

```
{
    "jsonrpc": "2.0",
    "method": "do.something",
    "params": {
        "output": [
            "id",
            "name"
        ],
        "interfaces": [
            "id",
            "name"
        ]
    },
    "id": 5,
    "auth": "1234ab123401624291e7d12572075e65"
}
```

**Comment by ybbus** [comment]
How sikmike,

this should be implemented in a fork since this is a special case and also not defined in the specification.

Best,
Alex

**Comment by hialvaro** [comment]
@sikmike I made a fork and added such feature: https://github.com/hialvaro/jsonrpc-with-auth
