### ISSUE TITLE
Outdated dependency

### ISSUE THREAD

**Issue by vault-thirteen** [ybbus/jsonrpc#56]
Hallo Alexander.

I am using your library and have found that one of the dependencies is outdated.
My IDE shows that there are updates for following package.

    github.com/stretchr/testify v1.8.1 -> v1.8.4

If there are no special reasons for not updating the version, it would be great to update them.

I also suggest adding a built-in GitHub feature called "Dependabot" which automatically informs repository owners about available updates. This feature saves me a lot of time for maintaining versions updated.

Danke !

**Comment by ybbus** [comment]
done
